# Generated by Django 3.0 on 2020-03-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200314_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlogin',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientlogin',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientlogin',
            name='budget',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientlogin',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientlogin',
            name='floors',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientlogin',
            name='mobile_no',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientlogin',
            name='plot_size',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
