# Generated by Django 3.0 on 2020-03-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200314_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientlogin',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='clientlogin',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
