# Generated by Django 3.0 on 2020-03-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200325_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientlogin',
            old_name='is_active',
            new_name='is_updated',
        ),
    ]
