# Generated by Django 3.0 on 2020-03-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20200325_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlogin',
            name='is_updated',
        ),
    ]
