# Generated by Django 3.0 on 2020-03-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_clientlogin_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlogin',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
