# Generated by Django 3.0 on 2020-04-05 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0008_auto_20200325_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlogin',
            name='project_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_created_at', models.DateTimeField(auto_now=True)),
                ('from_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_contractor', to=settings.AUTH_USER_MODEL)),
                ('to_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
