# Generated by Django 3.0 on 2020-04-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20200405_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='material',
            field=models.CharField(choices=[('with_material', 'With Material'), ('without_material', 'Without Material')], default='without_material', max_length=50),
        ),
    ]
