# Generated by Django 3.0 on 2020-04-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20200405_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='to_client',
        ),
        migrations.AddField(
            model_name='bid',
            name='to_client_mob',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
