# Generated by Django 3.0 on 2020-04-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20200406_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlogin',
            name='mobile_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
