# Generated by Django 3.0 on 2020-04-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_bid_contractor_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='contractor_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
