# Generated by Django 3.0 on 2020-04-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20200407_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='contractor_pk',
        ),
    ]
