# Generated by Django 3.0.5 on 2020-04-19 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0016_remove_bid_to_client_mob'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='to_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
