# Generated by Django 3.0.5 on 2020-04-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_bid_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='from_contractor_pk',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
