# Generated by Django 3.0 on 2020-03-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorlogin',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contractorlogin',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorlogin',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorlogin',
            name='occupation',
            field=models.CharField(choices=[('contractor', 'Contractor'), ('interior designer', 'Interior Designer'), ('map designer', 'Map Designer')], default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='contractorlogin',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='contractorlogin',
            name='sample_work_1',
            field=models.ImageField(blank=True, upload_to='sample_work_1'),
        ),
        migrations.AddField(
            model_name='contractorlogin',
            name='sample_work_2',
            field=models.ImageField(blank=True, upload_to='sample_work_2'),
        ),
        migrations.AddField(
            model_name='contractorlogin',
            name='sample_work_3',
            field=models.ImageField(blank=True, upload_to='sample_work_3'),
        ),
        migrations.AddField(
            model_name='contractorlogin',
            name='sample_work_4',
            field=models.ImageField(blank=True, upload_to='sample_work_4'),
        ),
        migrations.AddField(
            model_name='contractorlogin',
            name='sample_work_5',
            field=models.ImageField(blank=True, upload_to='sample_work_5'),
        ),
    ]
