# Generated by Django 3.0 on 2020-03-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contractor', '0003_auto_20200325_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorlogin',
            name='about_self',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
