# Generated by Django 3.0 on 2020-03-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contractor', '0004_contractorlogin_about_self'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorlogin',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
